version: '3'

services:
  server:
    container_name: offerize-server-dev
    image: strapi/strapi
    environment: 
      - DATABASE_HOST=db
    ports:
      - 1337:1337
    volumes:
      - ./server:/srv/app
    depends_on:
      - db
  db:
    container_name: offerize-db-dev
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
