#
# build environment
#
FROM node:latest as build

# build client
WORKDIR /client

COPY ./client/package.json .
COPY ./client/package-lock.json .
RUN npm install

COPY ./client .
RUN npm run build

#
# production environment
#
FROM nginx:stable-alpine

COPY --from=build /client/build /usr/share/nginx/html/client
COPY ./nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]