version: '3'

services:
  api:
    container_name: offerize-api-prod
    image: nionata/offerize:latest
    # ports:
      # - 1337:1337
    environment: 
      - DATABASE_HOST
      - DATABASE_PASSWORD
      - GOOGLE_KEY
  web:
    container_name: offerize-web-prod
    image: nionata/offerize-web:latest
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/offerize.xyz/fullchain.pem:/etc/letsencrypt/live/offerize.xyz/fullchain.pem
      - /etc/letsencrypt/live/offerize.xyz/privkey.pem:/etc/letsencrypt/live/offerize.xyz/privkey.pem

