name: Release Latest Version

on:
  release:
    types: [ published ]
    branches: [ master ]

jobs:
  # release-latest-client:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Invalidate client cache
  #     run: |
  #       aws cloudfront create-invalidation --distribution-id="$DISTRIBUTION" --paths "/*"
  #     env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  #       AWS_DEFAULT_REGION: us-east-1
  #       DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
  tag-and-push-server-image:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Tag latest api as release version
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nionata/offerize
          cache_froms: nionata/offerize:latest
          always_pull: true
          tag_with_ref: true
      - name: Tag latest web as release version
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nionata/offerize-web
          cache_froms: nionata/offerize-web:latest
          always_pull: true
          tag_with_ref: true
          dockerfile: Dockerfile.web