name: Release Latest Version

on:
  release:
    types: [ published ]
    branches: [ master ]

jobs:
  build-and-release-client:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install client dependencies
      run: cd client && npm install
    - name: Build client
      run: cd client && npm run build
      env:
        CI: false
    - name: Upload build to S3
      uses: nionata/upload-s3-action@v1.0.2
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'client/build'
        destination_dir: ''
  tag-and-push-server-image:
      runs-on: ubuntu-latest
      steps:
      - name: Pull the latest server image
        run: docker pull nionata/offerize:latest
      - name: Tag latest according to release
        run: docker tag nionata/offerize:latest nionata/offerize:${GITHUB_REF##*/}
      - name: Push tagged image
        run: docker push nionata/offerize:${GITHUB_REF##*/}
