name: Build and Update Server

on:
  push:
    branches: [ develop, master ]
    paths:
      - 'server/**'
      - '!client/**'
      - '!README.md'

jobs:
  build-and-update:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nionata/offerize
          cache_froms: nionata/offerize:latest
          always_pull: true
          tags: latest
      - name: Deploy latest image to EC2
        uses: appleboy/ssh-action@master
        env: 
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PERM_KEY }}
          script: |
            docker kill offerize-server-prod
            docker rm offerize-server-prod
            docker pull nionata/offerize:latest
            docker run --name offerize-server-prod -p 80:1337 -e DATABASE_HOST=$DATABASE_HOST -e DATABASE_PASSWORD=$DATABASE_PASSWORD -e GOOGLE_KEY=$GOOGLE_KEY nionata/offerize:latest